# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 25, 400, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 75, 400, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(50, 125, 400, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(50, 175, 400, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(50, 225, 400, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(50, 275, 400, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(225, 330, 50, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(225, 310, 50, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(225, 255, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(225, 205, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(225, 155, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(225, 105, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(225, 55, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(225, 5, 47, 13))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox.setItemText(10, _translate("MainWindow", "White"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "White"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "White"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "White"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "White"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "Orange"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "Yellow"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "Green"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "Blue"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "Violet"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "Grey"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "White"))
        self.label_2.setText(_translate("MainWindow", "Result:"))
        self.label_3.setText(_translate("MainWindow", "Band 6:"))
        self.label_4.setText(_translate("MainWindow", "Band 5:"))
        self.label_5.setText(_translate("MainWindow", "Band 4:"))
        self.label_6.setText(_translate("MainWindow", "Band 3:"))
        self.label_7.setText(_translate("MainWindow", "Band 2:"))
        self.label_8.setText(_translate("MainWindow", "Band 1:"))
